config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'pages#home'
  get 'about_us' => 'pages#about_us'
  get 'stores' => 'pages#stores'
  get '/storehouses/articles/list_subcategories'
  get 'subcategory_products' => 'admin/subcategories#show_products'
  get 'favoritos', to: 'whishlist_items#index'
  get "/storehouses/favorite_articles"
  get "/storehouses/favorite_clients"

  resources :whishlist_items do
    get 'create', to: 'whishlist_items#create'
  end


  # devise_scope :user do
  #   get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end

  namespace :admin do
    resources :storehouses
    resources :categories
    resources :subcategories
    resources :user, :controller => "user"
    get 'user_list' => 'user#user_index'
    get 'article_list' => 'user#article_index'
    get 'edit_user' => 'user#edit_user'
    patch 'update_user' => 'user#update_user'
  end

   namespace :storehouses do
    resources :articles do
      get "bindstore", to: "articles#bindstore",  as: "bindstore"
    end
  end

  resources :storehouses do
    get 'subcategories_list', on: :member
  end
end

# http://localhost:3000/storehouses/json/1.json
# http://localhost:3000/storehouses/article/json/1.json

app/models/subcategory.rb
# == Schema Information
#
# Table name: subcategories
#
#  id          :integer          not null, primary key
#  name        :string
#  category_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Subcategory < ActiveRecord::Base
  belongs_to :category
  has_many :articles
  validates :name, :category_id, presence: true
end

app/controllers/admin/subcategories_controller.rb
class Admin::SubcategoriesController < ApplicationController
  before_action :authenticate_user!, :except => [:show_products]
  before_action :admin_only, :except => [:show_products]

  def index
    @subcategories = Subcategory.all
  end

  def new
    @subcategory = Subcategory.new
  end

  def edit
    @subcategory = Subcategory.find(params[:id])
  end

  def create
    @subcategory = Subcategory.new(subcategory_params)
    if @subcategory.save
      flash[:notice] = "La subcategoría #{@subcategory.name} fue creada con éxito"
      redirect_to admin_subcategories_path
    else
      flash[:alert] = "Hubo un problema y la subcategoría no ha sido guardada correctamente"
      render :action => :new
    end
  end

  def update
    @subcategory = Subcategory.find(params[:id])
    if @subcategory.update(subcategory_params)
      flash[:notice] = "La subcategoría #{@subcategory.name} fue actualizada con éxito"
      redirect_to admin_subcategories_path
    else
      flash[:alert] = "Hubo un problema y la subcategoría no ha sido guardada correctamente"
      render :action => :edit
    end
  end

  def destroy
    @subcategory = Subcategory.find(params[:id])

    @subcategory.destroy
    redirect_to admin_subcategories_path
  end

  def show_products
    @subcategory = Subcategory.find(params[:subcategory_id])
    puts "#{@subcategory.name}!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
    @category = @subcategory.category
    puts "#{@category.name}!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
    @articles = @subcategory.articles
    @articles.each do |article|
      puts "#{article.name}!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
    end
    if @articles.count > 0
      @articles = @articles.paginate(:page => params[:page], :per_page => 12)
    else
      @articles = nil
    end
  end

  private
    def subcategory_params
      params.require(:subcategory).permit(:name, :category_id)
    end

  def admin_only
    unless current_user.admin?
      redirect_to root_path, :alert => "Lo sentimos, usted no posee permisos de administrador para acceder a esta ruta."
    end
  end

end

app/views/admin/subcategories/edit.html.erb
<style>
  label {
    margin-right: 10px
  }
</style>

<div class="container headerOffset">
  <div class="row">
    <div class="breadcrumbDiv col-lg-12">
      <ul class="breadcrumb">
        <li> <%= link_to "Home", root_path %></li>
        <li> <%= link_to "Subcategorías", new_admin_subcategory_path %></li>
        <li> <%= link_to "Subcategorías Registradas", admin_subcategories_path %> </li>
        <li class="active"> Editar una nueva subcategoría  </li>
      </ul>
    </div>
  </div>
  <%= form_for(@subcategory, url: admin_subcategory_path) do |subcategory| %>
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="row userInfo">
          <div class="col-md-6 col-sm-6 col-xs-12">
            <h1 class="section-title-inner"><span><i class="fa fa-lock"></i> Nueva Subcategoría </span></h1>
            <hr>

            <div class="form-group reg-email">
              <div>
                <%= subcategory.text_field :name, :autofocus => true, class: "form-control input", placeholder: "Nombre de la subcategoría", id: "login-user" %>
              </div>
            </div>

            <p><strong>Categoría a la que pertenece:</strong></p>

            <div class="form-group reg-email">
              <div>
                <% Category.all.each do |category| %>
                  <%= subcategory.radio_button :category_id, "#{category.id}" %>
                  <%= subcategory.label "#{category.name}" %>
                <% end %>
              </div>
            </div>


            <%= subcategory.submit "Actualizar Subcategoría", :class => 'btn btn-block btn-lg btn-primary' %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/subcategories/index.html.erb
<div class="container main-container headerOffset">
  <div class="row">
    <div class="breadcrumbDiv col-lg-12">
      <ul class="breadcrumb">
        <li> <%= link_to "Home", root_path %></li>
        <li> <%= link_to "Subcategorías", new_admin_subcategory_path %></li>
        <li class="active"> Subcategorías Registradas </li>

      </ul>
    </div>
  </div> <!--/.row-->

  <div class="row">
    <div class="col-lg-10 col-md-10 col-sm-7">
      <h1 class="section-title-inner"><span><i class="glyphicon glyphicon-shopping-cart"></i> Lista de Subcategorías Registradas </span></h1>
      <div class="row userInfo">
        <div class="col-lg-12">
          <h2 class="block-title-2"> Subcategorías registradas en nuestra plataforma: </h2>
        </div>
        <div class="col-xs-12 col-sm-12 col-sm-offset-2">
          <table>
            <tbody>

            <% @subcategories.each do |subcategory| %>

              <tr class="CartProduct">
                <td style="width:30%">
                  <div>
                    <strong>Nombre de la Subcategoría</strong> <br>
                    <p><%= subcategory.name %></p>
                  </div>
                </td>

                <td class="CartDescription" style="width:30%">
                  <div>
                    <strong>Categoría a la que pertenece:</strong> <br>
                    <p><%= subcategory.category.name %></p>
                  </div>
                </td>

                <td  class="delete" style="width:20%">
                  <%= link_to "<i class='glyphicon glyphicon-edit fa-2x'></i>".html_safe, edit_admin_subcategory_path(subcategory.id), class: "btn btn-warning", title: "Editar Tienda" %>
                  <%= link_to "<i class='glyphicon glyphicon-trash fa-2x'></i>".html_safe, admin_subcategory_path(subcategory.id), method: :delete, data: { confirm: '¿Estás seguro?' }, class: "btn btn-danger", title: "Eliminar Tienda" %>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>

        <div class="col-lg-12 clearfix">
          <ul class="pager">
            <li class="previous pull-right"><%= link_to "<i class='fa fa-home'></i> Regresar a la Tienda".html_safe, root_path %></li>


            <li class="next pull-left"><%= link_to "<i class='fa fa-plus-square'></i> Crear Una Nueva Subcategoría".html_safe, new_admin_subcategory_path %></li>
          </ul>
        </div>

      </div>
      <!--/row end-->

    </div>
    <div class="col-lg-3 col-md-3 col-sm-5"> </div>
  </div>
  <!--/.row-->
  <div style="clear:both"></div>
</div> <!-- /main-container -->

<div class="gap"> </div>

app/views/admin/subcategories/new.html.erb
<style>
  label {
    margin-right: 10px
  }

  .categories div {
    display: inline-block;
  }
</style>

<div class="container headerOffset">
  <div class="row">
    <div class="breadcrumbDiv col-lg-12">
      <ul class="breadcrumb">
        <li> <%= link_to "Home", root_path %></li>
        <li> <%= link_to "Subcategorías", new_admin_subcategory_path %></li>
        <li> <%= link_to "Subategorías Registradas", admin_subcategories_path %> </li>
        <li class="active"> Crear una nueva subcategoría  </li>
      </ul>
    </div>
  </div>
  <%= form_for(@subcategory, url: admin_subcategories_path) do |subcategory| %>
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="row userInfo">
          <div class="col-md-6 col-sm-6 col-xs-12">
            <h1 class="section-title-inner"><span><i class="fa fa-lock"></i> Nueva Subcategoría </span></h1>
            <hr>

            <div class="form-group reg-email">
              <div>
                <%= subcategory.text_field :name, :autofocus => true, class: "form-control input", placeholder: "Nombre de la subcategoría", id: "login-user" %>
              </div>
            </div>

            <p><strong>Categoría a la que pertenece:</strong></p>

            <div class="form-group reg-email">
              <div class="categories">
                <% Category.all.each do |category| %>
                  <%= subcategory.radio_button :category_id, "#{category.id}" %>
                  <%= subcategory.label "#{category.name}" %>
                <% end %>
              </div>
            </div>


            <%= subcategory.submit "Registrar Nueva Subcategoría", :class => 'btn btn-block btn-lg btn-primary' %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/subcategories/show_products.html.erb
<div class="container main-container headerOffset">

  <!-- Main component call to action -->

  <div class="row">
    <div class="breadcrumbDiv col-lg-12">
      <ul class="breadcrumb">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to @category.name, "#Por definir esta ruta, enviarlo al show de category con todos los productoss" %></li>
        <li class="active"><%= @subcategory.name %></li>
      </ul>
    </div>
  </div>  <!-- /.row  -->

  <div class="row">

   <!--left column-->

    <div class="col-lg-3 col-md-3 col-sm-12">
      <div class="panel-group" id="accordionNo">
       <!--Category-->
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
            <a data-toggle="collapse"  href="#collapseCategory" class="collapseWill">
            <span class="pull-left"> <i class="fa fa-caret-right"></i></span> Categoría
            </a>
            </h4>
          </div>

          <div id="collapseCategory" class="panel-collapse collapse in">
            <div class="panel-body">
              <ul class="nav nav-pills nav-stacked tree">
                <li class="active dropdown-tree open-tree" > <a  class="dropdown-tree-a" > <span class="badge pull-right"><%= @category.subcategories.count %></span> <%= @category.name.upcase %> </a>
                  <ul class="category-level-2 dropdown-menu-tree">
                    <li class="dropdown-tree open-tree"><%= @subcategory.name.capitalize %></li>
                    <% @category.subcategories.each do |subcategory| %>
                      <% unless subcategory.id == @subcategory.id %>
                        <li><%= link_to subcategory.name, subcategory_products_path(:subcategory_id => subcategory.id) %></li>
                      <% end %>
                    <% end %>
                  </ul>
                </li>
              </ul>

              <% Category.all.each do |category| %>
                <% unless category.id == @category.id %>
                  <ul class="nav nav-pills nav-stacked tree">
                    <li class="active dropdown-tree" > <a class="dropdown-tree-a"> <span class="badge pull-right"><%= category.subcategories.count %></span> <%= category.name.upcase %> </a>
                      <ul class="category-level-2 dropdown-menu-tree">
                        <% category.subcategories.each do |subcategory| %>
                          <li><%= link_to subcategory.name, subcategory_products_path(:subcategory_id => subcategory.id) %></li>
                        <% end %>
                      </ul>
                    </li>
                  </ul>
                <% end %>
              <% end %>
            </div>
          </div>
        </div> <!--/Category menu end-->
      </div>

    </div>


    <!--right column-->
    <div class="col-lg-9 col-md-9 col-sm-12">

      <div class="w100 clearfix category-top">
        <h2> PRODUCTOS EN ESTA SECCIÓN </h2>
        <div class="categoryImage"> <img src="<%= asset_path('site/subcategory.jpg') %>" class="img-responsive" alt="img"> </div>
      </div><!--/.category-top-->

      <div class="w100 productFilter clearfix">
        <% if @subcategory.articles.count > 1 || @subcategory.articles.count == 0 %>
          <p class="pull-left"> Mostrando <strong><%= @subcategory.articles.count %></strong> artículos </p>
        <% else %>
          <p class="pull-left"> Mostrando <strong><%= @subcategory.articles.count %></strong> artículo </p>
        <% end %>
      </div>

      <div class="row  categoryProduct xsResponse clearfix">
        <% if @articles.blank? %>
          <h1 class="text-center">Esta categoria no posee productos asociados</h1>
        <% else %>
          <% @articles.each do |article| %>
            <div class="item col-sm-4 col-lg-4 col-md-4 col-xs-6">
              <div class="product">
                <%= link_to "<i class='glyphicon glyphicon-heart'></i>".html_safe, whishlist_item_create_path(article), class: "add-fav" %>
                <div class="image">
                  <div class="quickview">
                    <a class="btn btn-lg btn-quickview" modal-id="article-<%= article.id %>" > Vista Rapida </a>
                  </div>
                  <%= link_to "<img src='#{article.article_images.first.image.url(:medium)}' alt='img' class='img-responsive'>".html_safe, storehouses_article_path(article.id) %>
                  <!-- <div class="promotion"> <span class="new-product"> NEW</span> <span class="discount">15% OFF</span> </div> -->
                </div>
                <div class="description">
                  <h4><a href="product-details.html"><%= article.name %></a></h4>
                  <div class="grid-description">
                    <p><%= article.details %></p>
                  </div>
                  <div class="list-description">
                    <h4><%= link_to article.name, storehouses_article_path(article.id) %></h4>
                    <p><%= article.details %> </p>
                  </div>
                </div>
                <div class="price"> <span>$ <%= number_to_currency(article.price, unit: "", precision: 0) %></span> </div>
                <div class="action-control">
                  <%= link_to "<span class='add2cart'><i class='glyphicon glyphicon-shopping-cart'></i> Lista de deseos</span>".html_safe, whishlist_item_create_path(article), class: "btn btn-primary" %>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div> <!--/.categoryProduct || product content end-->

      <div class="w100 categoryFooter">
        <div class="pagination pull-left no-margin-top">
        </div>
        <div class="pull-right pull-right  col-sm-4 col-xs-12 no-padding text-right text-left-xs">
          <% if @articles != nil %>
            <%= will_paginate @articles, :previous_label => 'Página Anterior', :next_label => 'Página Siguiente' %>
          <% end %>
          <!-- <p>Showing 1–450 of 12 results</p> -->
        </div>
        </div>
      </div> <!--/.categoryFooter-->
    </div><!--/right column end-->
  </div><!-- /.row  -->
</div>
<!-- /main container -->