config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'pages#home'
  get 'about_us' => 'pages#about_us'
  get 'stores' => 'pages#stores'
  get '/storehouses/articles/list_subcategories'
  get 'subcategory_products' => 'admin/subcategories#show_products'
  get 'favoritos', to: 'whishlist_items#index'
  get "/storehouses/favorite_articles"
  get "/storehouses/favorite_clients"

  resources :whishlist_items do
    get 'create', to: 'whishlist_items#create'
  end


  # devise_scope :user do
  #   get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end

  namespace :admin do
    resources :storehouses
    resources :categories
    resources :subcategories
    resources :user, :controller => "user"
    get 'user_list' => 'user#user_index'
    get 'article_list' => 'user#article_index'
    get 'edit_user' => 'user#edit_user'
    patch 'update_user' => 'user#update_user'
  end

   namespace :storehouses do
    resources :articles do
      get "bindstore", to: "articles#bindstore",  as: "bindstore"
    end
  end

  resources :storehouses do
    get 'subcategories_list', on: :member
  end
end

# http://localhost:3000/storehouses/json/1.json
# http://localhost:3000/storehouses/article/json/1.json

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime
#  updated_at             :datetime
#  role                   :integer
#  avatar_file_name       :string
#  avatar_content_type    :string
#  avatar_file_size       :integer
#  avatar_updated_at      :datetime
#  provider               :string
#  uid                    :string
#

# Hirb.enable :output => {"User"=>{:options=>{:fields=>%w{id email role}}}}

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "http://i592.photobucket.com/albums/tt5/Mardini03/765-default-avatar.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  validates_uniqueness_of :email
  has_one :storehouse, dependent: :destroy
  has_many :wishlist_items, dependent: :destroy
  enum role: [ :user, :tent, :admin]
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:facebook]
  accepts_nested_attributes_for :storehouse, :reject_if => :all_blank, allow_destroy: true
  validates_associated :storehouse

	after_initialize :set_default_role, :if => :new_record?
	def set_default_role
    self.role ||= :user
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      # user.name = auth.info.name   # assuming the user model has a name
      avatar_url = auth.info.image
      avatar_url.gsub!("http","https")
      user.avatar = avatar_url # assuming the user model has an image
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/admin/user_controller.rb
class Admin::UserController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_or_tent_only?, :only =>[:show, :edit, :update]
  before_action :admin_only, :except => [:edit_user,:update_user,:show,:edit,:update]

	def index
		@storehouses = Storehouse.all
	end

  def show
    @user = User.find(params[:id])
    @storehouse = @user.storehouse
  end

  def new
    @user = User.new
    @user.build_storehouse
  end

  def create
    @user = User.new(user_params)
    @user.role = "tent"
    if @user.save
      flash[:notice] = "El usuario #{@user.email} fue creado con éxito"
      redirect_to admin_user_index_path
    else
      if @user.errors.any?
        flash[:alert] = @user.errors.full_messages.first
      else
        flash[:alert] = "Ha ocurrido un error y el usuario #{@user.email}, no ha sido almacenado"
      end
      render :action => 'new'
    end
  end

  # Edit and update for storehouses
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "El usuario #{@user.email} fue actualizado con éxito"
      redirect_to admin_user_index_path if current_user.admin?
      redirect_to admin_user_path(@user) if current_user.tent?
    else
      flash[:alert] = "Ha ocurrido un error y el usuario #{@user.email}, no ha sido almacenado"
      render :action => 'edit'
    end
  end

  # Edit and update for users
  def edit_user
    @user = User.find(params[:id])
  end

  def update_user
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "El usuario #{@user.email} fue actualizado con éxito"
      if current_user.admin?
        sign_in @user, :bypass => false
        redirect_to admin_user_list_path
      else
        redirect_to root_path
      end
    else
      flash[:alert] = "Ha ocurrido un error y el usuario #{@user.email}, no ha sido almacenado"
      render :action => 'edit_user'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_user_index_path
  end

	# Metodo para listar todos los usuarios de la plataforma
	def user_index
		puts "#{params[:user]} - #{params[:tent]} - #{params[:admin]}!!!!!!!!!!!!!!!!!!!!!!!!!!"
		# Filtro para seleccion un rol especifico de usuarios
		if params[:user].present?
		  @users = User.where(role: 0)
		elsif params[:tent].present?
		  @users = User.where(role: 1)
		elsif params[:admin].present?
		  @users = User.where(role: 2)
		else
			#Bandera para mostrar lista vacia
			@vacio = true
		end
	end

	def article_index
		@articles = Article.all
    @articles = Article.paginate(:page => params[:page], :per_page => 10)
	end

	private
		def user_params
  		params.require(:user).permit(:email, :password, :password_confirmation, storehouse_attributes: [:id,:name,:address,:avatar,:description,:email,:telephone,:user_id,:whatsapp,:_destroy])
		end

    def admin_or_tent_only?
      unless current_user.tent? || current_user.admin?
        redirect_to root_path, :alert => "Lo sentimos, usted no es vendedor de articulos para acceder a esta ruta."
      end
    end

    def admin_only
      unless current_user.admin?
        redirect_to root_path, :alert => "Lo sentimos, usted no posee permisos de administrador para acceder a esta ruta."
      end
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
	before_action :authenticate_user!
	before_action :admin_only

	def new
		@user = User.new
		storehouse = @user.storehouses.build
	end 

	def create
  	@user = User.new(user_params)
  	@user.role = "tent"
	  if @user.save
  	  flash[:notice] = "El usuario #{@user.email} fue creado con exito"
  	  redirect_to user_index_path
  	else
  		flash[:alert] = "Ha ocurrido un error y el usuario #{@user.email}, no ha sido almacenado"
    	render :action => 'new'
  	end
	end

	def index
		@storehouses = Storehouse.all
	end

	private
		def user_params
  		params.require(:user).permit(:email, :password, :password_confirmation, storehouses_attributes: [:id,:name,:address,:avatar,:description,:email,:telephone,:user_id,:whatsapp,:_destroy])
		end
		
		def admin_only
    unless current_user.admin?
      redirect_to root_path, :alert => "Lo sentimos, usted no posee permisos de administrador para acceder a esta ruta."
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
	def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/user/_admin_nav.html.erb
<li> <%= link_to "Home", root_path %></li>
          <li> <%= link_to "Gestor de Tiendas", new_admin_user_path %></li>
          <li> <%= link_to "Tiendas Registradas", admin_user_index_path %> </li>

app/views/admin/user/_tent_nav.html.erb
<li> <%= link_to "Home", root_path %></li>
          <li> <%= link_to "Mi Tienda", admin_user_path(current_user.id) %></li>

app/views/admin/user/article_index.html.erb
<div class="container main-container headerOffset">
  <div class="row">
    <div class="breadcrumbDiv col-lg-12">
      <ul class="breadcrumb">
        <li> <%= link_to "Home", root_path %></li>
        <li class="active"> Artículos registrados </li>
      </ul>
    </div>
  </div> <!--/.row-->
  
  <div class="row">
    <div class="col-lg-10 col-md-10 col-sm-7">
      <h1 class="section-title-inner"><span><i class="glyphicon glyphicon-shopping-cart"></i> Lista de Artículos Registrados </span></h1>
      <div class="row userInfo">
        <div class="col-lg-12">
          <h2 class="block-title-2">Estos son todos los artículos que hay registrados en el sistema: </h2>
        </div>
        <div class="col-xs-12 col-sm-12">
          <table>
            <tbody>
            <% @articles.each do |article| %>
              <tr class="CartProduct">
                <td style="width:10%" class="CartProductThumb">
                  <div> <%= link_to image_tag(article.article_images.first.image.url), storehouses_article_path(article.id) %></div></td>
                <td style="width:30%"><div class="CartDescription">
                  <h4><%= link_to article.name, storehouses_article_path(article.id) %></h4>
                  <span><%= article.subtitle %></span>
                  <div class="price"> <span><%= number_to_currency(article.price, precision: 0) %></span> </div>
                  </div></td>
                <td style="width:60%">
                  <%= link_to "<i class='glyphicon glyphicon-eye-open fa-2x'></i>".html_safe, storehouses_article_path(article.id), class: "btn btn-success", title: "Ver Producto" %>
                  <%= link_to "<i class='glyphicon glyphicon-edit fa-2x'></i>".html_safe, edit_storehouses_article_path(article.id), class: "btn btn-warning", title: "Editar Producto" %>
                  <%= link_to storehouses_article_path(article.id), title: "Eliminar Producto", method: :delete, data: { confirm: '¿Esta seguro que desea eliminar el curso?' }, class: "btn btn btn-ar btn-danger" do %><span><i class='glyphicon glyphicon-trash fa-2x'></i></span><% end %>
                </td>                
              </tr>
            <% end %>                                      
            </tbody>
          </table>
        </div>
      </div>
      <!--/row end--> 
      <div class="pull-right pull-right  col-sm-4 col-xs-12 no-padding text-right text-left-xs">
        <%= will_paginate @articles, :previous_label => 'Página Anterior', :next_label => 'Página Siguiente' %>
        <!-- <p>Showing 1–450 of 12 results</p> -->
      </div>     
    </div>
    <div class="col-lg-3 col-md-3 col-sm-5"> </div>
  </div>
  <!--/.row-->
  <div style="clear:both"></div>
</div> <!-- /main-container -->

<div class="gap"> </div>

app/views/admin/user/edit.html.erb
<div class="container headerOffset">
  <div class="row">
    <div class="breadcrumbDiv col-lg-12">
      <ul class="breadcrumb">
        <% if current_user.admin? %>
          <%= render 'admin_nav' %>
          <li class="active">Editar tienda</li>
        <% else %>
          <%= render 'tent_nav' %>
          <li class="active">Editar tienda</li>
        <% end %>
      </ul>
    </div>
  </div>
  <%= form_for(@user, url: {action: "update", params: {id: @user.id}}) do |user| %>
          <%= user.fields_for :storehouse do |storehouse| %>
            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
              <h1 class="section-title-inner"><span><i class="fa fa-shopping-cart"></i> Información de Tienda - Editar Tienda </span></h1>
              <h2 class="block-title-2"><span>Ingresa los datos que quieras modificar de la tienda</span></h2>

              <div class="form-group reg-email">
                <div>
                  <%= storehouse.text_field :name, :autofocus => true, class: "form-control input", placeholder: "Nombre de la tienda" %>
                </div>
              </div>

              <div class="form-group reg-email">
                <div>
                  <%= storehouse.label :avatar, "IMAGEN DE LA TIENDA:" %>
                  <%= storehouse.file_field :avatar, class: "input-file" %>
                </div>
              </div>

              <div class="form-group reg-email">
                <div>
                  <%= storehouse.text_field :address, :autofocus => true, class: "form-control input", placeholder: "Dirección de la tienda" %>
                </div>
              </div>

              <div class="form-group reg-email">
                <div>
                  <%= storehouse.email_field :email, class: "form-control input", placeholder: "Email", id: "login-user" %>
                </div>
              </div>

              <div class="form-group reg-email">
                <div>
                  <%= storehouse.text_area :description, :autofocus => true, class: "form-control input", rows: 5,placeholder: "Descripción de la tienda" %>
                </div>
              </div>

              <div class="form-group reg-email">
                <div>
                  <%= storehouse.text_field :telephone, class: "form-control input", placeholder: "Telefono" %>
                </div>
              </div>

              <div class="form-group reg-email">
                <div>
                  <%= storehouse.text_field :whatsapp, class: "form-control input", placeholder: "WhatsApp" %>
                </div>
              </div>
            </div>
          <% end %>
          <div class="row">
            <div class="col-md-6 col-md-offset-3">
              <%= user.submit "Actualizar Tienda", :class => 'btn btn-block btn-lg btn-primary' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/user/edit_user.html.erb
<div class="container headerOffset">
  <div class="row">
    <div class="breadcrumbDiv col-lg-12">
      <ul class="breadcrumb">
        <li> <%= link_to "Home", root_path %></li>
        <li class="active"> Editar Información de Usuario </li>
      </ul>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-12">
      <h1 class="section-title-inner"><span><i class="fa fa-lock"></i> Actualizar datos</span></h1>
      <div class="row userInfo">
        <div class="col-md-12">          
          <h2 class="block-title-2"><span>ingresa tus datos personales para que sean actualizados</span></h2>
          <%= form_for(@user,  url: {action: "update_user", params: {id: @user.id}}) do |f| %>            
            <div class="form-group reg-email">
              <div>
                <%= f.email_field :email, :autofocus => true, class: "form-control input", placeholder: "Email", id: "login-user" %>
              </div>
            </div>

            <% if @user.provider %>           
              <div class="form-group reg-password">
                <div>
                  <h4 class="text-center">Usuario registrado a través de <%= @user.provider.humanize %>, por lo tanto no tiene una contraseña asociada a esta plataforma.</h4>
                </div>
              </div> 
            <% else %>
              <div class="form-group reg-password">
                <div>
                  <%= f.password_field :password, class: "form-control input", placeholder: "Contraseña - Mínimo 8 caracteres" %>
                </div>
              </div> 
              <div class="form-group reg-password">
                <div>
                  <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control input", placeholder: "Confirmar contraseña" %>
                </div>
              </div>
            <% end %>
            <div >
              <div >
                <%= f.submit "Editar Información de Usuario", :class => 'btn btn-block btn-lg btn-primary' %>
              </div>
            </div>
            <!--userForm--> 
          <% end %>
        </div> 
      </div>
    </div>
  </div>
</div>

app/views/admin/user/index.html.erb
<div class="container main-container headerOffset">
  <div class="row">
    <div class="breadcrumbDiv col-lg-12">
      <ul class="breadcrumb">
        <li> <%= link_to "Home", root_path %></li>
        <li> <%= link_to "Gestor de Tiendas", new_admin_user_path %></li>
        <li class="active"> Tiendas Registradas </li>

      </ul>
    </div>
  </div> <!--/.row-->

  <div class="row">
    <div class="col-lg-10 col-md-10 col-sm-7">
      <h1 class="section-title-inner"><span><i class="glyphicon glyphicon-shopping-cart"></i> Lista de Tiendas Registradas </span></h1>
      <div class="row userInfo">
        <div class="col-lg-12">
          <h2 class="block-title-2"> Tiendas registradas en nuestra plataforma: </h2>
        </div>
        <div class="col-xs-12 col-sm-12">
          <table>
            <tbody>

						<% @storehouses.each do |storehouse| %>

							<tr class="CartProduct">
                <td style="width:30%">
                  <div>
                    <p><%= storehouse.user.email %></p>
                    <p><%= storehouse.user.email %></p>
                    <p>Informacion restante del usuario</p>
                  </div>
                </td>
                <td style="width:10%" class="CartProductThumb text-center">
                	<div>
                    <a href="#"><%= image_tag storehouse.avatar.url %></a>
                  </div>
                </td>
                <td style="width:40%">
                  <div class="CartDescription">
                    <h4><a href="product-details.html"><%= storehouse.name %></a></h4>
                    <span class="size"><%= storehouse.address %></span>
                    <div class="price"> <span><%= storehouse.email %></span> </div>
                  </div>
                </td>
                <td  class="delete" style="width:20%">
                  <%= link_to "<i class='glyphicon glyphicon-eye-open fa-2x'></i>".html_safe, admin_user_path(storehouse.user_id), class: "btn btn-success", title: "Ver Tienda" %>
                  <%= link_to "<i class='glyphicon glyphicon-edit fa-2x'></i>".html_safe, edit_admin_user_path(storehouse.user_id), class: "btn btn-warning", title: "Editar Tienda" %>
                  <%= link_to "<i class='glyphicon glyphicon-trash fa-2x'></i>".html_safe, admin_user_path(storehouse.user_id), method: :delete, data: { confirm: '¿Estás seguro?' }, class: "btn btn-danger", title: "Eliminar Tienda" %>
                </td>
              </tr>
						<% end %>
            </tbody>
          </table>
        </div>

        <div class="col-lg-12 clearfix">
          <ul class="pager">
            <li class="previous pull-right"><%= link_to "<i class='fa fa-home'></i> Regresar a la Tienda".html_safe, root_path %></li>


            <li class="next pull-left"><%= link_to "&larr; Crear Una Nueva Tienda".html_safe, new_admin_user_path %></li>
          </ul>
        </div>

      </div>
      <!--/row end-->

    </div>
    <div class="col-lg-3 col-md-3 col-sm-5"> </div>
  </div>
  <!--/.row-->
  <div style="clear:both"></div>
</div> <!-- /main-container -->

<div class="gap"> </div>

app/views/admin/user/new.html.erb
<div class="container headerOffset">
  <div class="row">
    <div class="breadcrumbDiv col-lg-12">
      <ul class="breadcrumb">
        <li> <%= link_to "Home", root_path %></li>
        <li class="active"> Crear un nuevo registro de tienda  </li>
      </ul>
    </div>
  </div>
  <%= form_for(@user, url: admin_user_index_path) do |user| %>
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="row userInfo">
          <div class="col-md-6 col-sm-6 col-xs-12">
            <h1 class="section-title-inner"><span><i class="fa fa-lock"></i> Autenticación - Registrar Propietario de la tienda</span></h1>
            <h2 class="block-title-2"><span>ingresa los datos de usuario, este sera propietario del establecimiento y accedera a la plataforma con la siguiente información</span></h2>

            <div class="form-group reg-email">
              <div>
                <%= user.email_field :email, :autofocus => true, class: "form-control input", placeholder: "Email", id: "login-user" %>
              </div>
            </div>

            <div class="form-group reg-password">
              <div>
                <%= user.password_field :password, class: "form-control input", placeholder: "Contraseña - Mínimo 8 caracteres" %>
              </div>
            </div>

            <div class="form-group reg-password">
              <div>
                <%= user.password_field :password_confirmation, autocomplete: "off", class: "form-control input", placeholder: "Confirmar contraseña" %>
              </div>
            </div>
          </div>
          <%= user.fields_for :storehouse do |storehouse| %>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <h1 class="section-title-inner"><span><i class="fa fa-shopping-cart"></i> Información de Registro - Nueva Tienda </span></h1>
              <h2 class="block-title-2"><span>ingresa los datos para proceder con el registro de la tienda</span></h2>

              <div class="form-group reg-email">
                <div>
                  <%= storehouse.text_field :name, :autofocus => true, class: "form-control input", placeholder: "Nombre de la tienda" %>
                </div>
              </div>

              <div class="form-group reg-email">
                <div>
                  <%= storehouse.label :avatar, "IMAGEN DE LA TIENDA:" %>
                  <%= storehouse.file_field :avatar, required: true, class: "input-file" %>
                </div>
              </div>

              <div class="form-group reg-email">
                <div>
                  <%= storehouse.text_field :address, :autofocus => true, class: "form-control input", placeholder: "Dirección de la tienda" %>
                </div>
              </div>

              <div class="form-group reg-email">
                <div>
                  <%= storehouse.email_field :email, class: "form-control input", placeholder: "Email", id: "login-user" %>
                </div>
              </div>

              <div class="form-group reg-email">
                <div>
                  <%= storehouse.text_area :description, :autofocus => true, class: "form-control input", rows: 5,placeholder: "Descripción de la tienda" %>
                </div>
              </div>

              <div class="form-group reg-email">
                <div>
                  <%= storehouse.text_field :telephone, class: "form-control input", placeholder: "Telefono" %>
                </div>
              </div>

              <div class="form-group reg-email">
                <div>
                  <%= storehouse.text_field :whatsapp, class: "form-control input", placeholder: "WhatsApp" %>
                </div>
              </div>
            </div>
          <% end %>
          <div class="row">
            <div class="col-md-8 col-md-offset-2">
              <%= user.submit "Registrar Nueva Tienda", :class => 'btn btn-block btn-lg btn-primary' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/user/show.html.erb
<div class="container headerOffset">
  <div class="row">
    <div class="breadcrumbDiv col-lg-12">
      <ul class="breadcrumb">
        <% if current_user.admin? %>
          <%= render 'admin_nav' %>
          <li class="active"><%= @storehouse.name %></li>
        <% else %>
          <%= render 'tent_nav' %>
          <li class="active"><%= @storehouse.name %></li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="row userInfo">
        <div class="col-md-6 col-sm-6 col-xs-12">
          <h1 class="section-title-inner"><span><i class="fa fa-lock"></i> Información del Propietario</span></h1>
          <hr>
          <p> <strong>Email:</strong> <br>
            <%= @user.email %>
          </p>
          <ul class="pager">
            <% if current_user.admin? %>
              <li class="next pull-left"><%= link_to "&larr; Regresar".html_safe, admin_user_index_path %></li>
            <% else %>
              <li class="next pull-left"><%= link_to "&larr; Regresar".html_safe, root_path %></li>
            <% end %>
          </ul>

        </div>
          <div class="col-md-6 col-sm-6 col-xs-12">
            <h1 class="section-title-inner"><span><i class="fa fa-shopping-cart"></i> Información de la Tienda </span></h1>
            <hr>

            <p>
              <strong>Nombre:</strong> <br>
              <%= @storehouse.name %>
            </p>

            <p>
              <strong>Imagen de la tienda:</strong> <br>
              <%= image_tag @storehouse.avatar.url, width: '20%' %>
            </p>

            <p>
              <strong>Dirección:</strong> <br>
              <%= @storehouse.address %>
            </p>

            <p>
              <strong>Email de la tienda:</strong> <br>
              <%= @storehouse.email %>
            </p>

            <p>
              <strong>Descripción:</strong> <br>
              <%= @storehouse.description %>
            </p>

            <p>
              <strong>Teléfono:</strong> <br>
              <%= @storehouse.telephone %>
            </p>

            <p>
              <strong>Whatsapp:</strong> <br>
              <%= @storehouse.whatsapp %>
            </p>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/user/user_index.html.erb
<div class="container main-container headerOffset">
  <div class="row">
    <div class="breadcrumbDiv col-lg-12">
      <ul class="breadcrumb">
        <li> <%= link_to "Home", root_path %></li>
        <li class="active"> Usuarios registrados </li>
      </ul>
    </div>
  </div> <!--/.row-->
  
  <div class="row">
    <div class="col-lg-10 col-md-10 col-sm-7">
      <h1 class="section-title-inner"><span><i class="glyphicon glyphicon-shopping-cart"></i> Listado de usuarios registrados en la plataforma</span></h1>        
    </div> 

    <div class="row userInfo">
      <div class="col-lg-12">
        <h2 class="block-title-2">Seleccione una categoría para listar los usuariados registrados en la plataforma: </h2>
        
        <!-- BOTONES PARA FILTRAR EL LISTADO DE USUARIOS BAJO UNA CATEGORÍA ESPECÍFICA -->
        <%= form_tag admin_user_list_path, method: :get do %>
          <%= hidden_field_tag :user, "USUARIOS"  %>
          <div class="col-xs-2 action form-group">
            <%= submit_tag "Listar Usuarios", name: nil, class: "btn btn-lg btn-success" %>          
          </div>
        <% end %> 

        <%= form_tag admin_user_list_path, method: :get do %>
          <%= hidden_field_tag :tent, "TIENDAS"  %>
          <div class=" col-xs-2 action form-group">
            <%= submit_tag "Listar Tiendas", name: nil, class: "btn btn-lg btn-success" %>         
          </div>
        <% end %> 

        <%= form_tag admin_user_list_path, method: :get do %>
          <%= hidden_field_tag :admin, "ADMINISTRADORES"  %>
          <div class="col-xs-2 action form-group">
            <%= submit_tag "Listar Administradores", name: nil, class: "btn btn-lg  btn-success" %>         
          </div>
        <% end %>

      </div>

      <% if @vacio %>
        <div class="col-xs-12 col-sm-12">
          <br><br><br><br>
          <h1 class="text-center">Seleccion un tipo de usuario para cargar los registros existentes</h1>
        </div>
      <% else %>
        <div class="col-xs-12 col-sm-12">
          <table>
            <tbody>
            <% @users.each do |user| %>
              <tr class="CartProduct">
                <td style="width:30%">
                  <div>
                    <p><%= user.email %></p>
                    <p>Informacion restante del usuario</p>
                  </div>
                </td>
                <td style="width:10%" class="CartProductThumb text-center">
                  <div> 
                    <a href="#"><%= image_tag user.avatar.url %></a> 
                  </div>
                </td>
                <td style="width:40%">
                  <div class="CartDescription">
                    <h4><a href="product-details.html"><%= user.email %></a></h4>
                    <div class="price"> <span><%= user.role.humanize %></span> </div>
                  </div>
                </td>               
                <td  class="delete" style="width:20%">
                  <%= link_to "<i class='glyphicon glyphicon-edit fa-2x'></i>".html_safe, admin_edit_user_path(:id => user.id), class: "btn btn-warning", title: "Editar Usuario" %>
                  <%= link_to "<i class='glyphicon glyphicon-trash fa-2x'></i>".html_safe, admin_user_path(user.id), method: :delete, data: { confirm: '¿Estás seguro que desea eliminar este usuario?' }, class: "btn btn-danger", title: "Eliminar Usuario" %>                                   
                </td>
              </tr> 
            <% end %>                                      
            </tbody>
          </table>
        </div>
      <% end %>
      
    </div>
  </div>
  <!--/.row-->
  <div style="clear:both"></div>
</div> <!-- /main-container -->

<div class="gap"> </div>