config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'pages#home'
  get 'about_us' => 'pages#about_us'
  get 'stores' => 'pages#stores'
  get '/storehouses/articles/list_subcategories'
  get 'subcategory_products' => 'admin/subcategories#show_products'
  get 'favoritos', to: 'whishlist_items#index'
  get "/storehouses/favorite_articles"
  get "/storehouses/favorite_clients"

  resources :whishlist_items do
    get 'create', to: 'whishlist_items#create'
  end


  # devise_scope :user do
  #   get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end

  namespace :admin do
    resources :storehouses
    resources :categories
    resources :subcategories
    resources :user, :controller => "user"
    get 'user_list' => 'user#user_index'
    get 'article_list' => 'user#article_index'
    get 'edit_user' => 'user#edit_user'
    patch 'update_user' => 'user#update_user'
  end

   namespace :storehouses do
    resources :articles do
      get "bindstore", to: "articles#bindstore",  as: "bindstore"
    end
  end

  resources :storehouses do
    get 'subcategories_list', on: :member
  end
end

# http://localhost:3000/storehouses/json/1.json
# http://localhost:3000/storehouses/article/json/1.json

app/views/pages/_login_modal.html.erb
<!-- Modal Login start -->
<div class="modal signUpContent fade" id="ModalLogin" tabindex="-1" role="dialog" >
  <div class="modal-dialog ">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"> &times; </button>
        <h3 class="modal-title-site text-center" > INICIAR SESIÓN </h3>
      </div>
      <div class="modal-body">
        <div class="control-group">
          <%= link_to "Inicia sesión con Facebook", user_omniauth_authorize_path(:facebook), class: "fb_button btn  btn-block btn-lg" %>
        </div>        
        <h5 style="padding:10px 0 10px 0;" class="text-center"> O COMPLETA TUS DATOS DE ACCESO </h5>

        <%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
          <div class="form-group login-username">
            <div>
              <%= f.email_field :email, :autofocus => true, class: "form-control input", placeholder: "Email", id: "login-user" %>
            </div>
          </div>
          
          <div class="form-group login-password">
            <div>
              <%= f.password_field :password, class: "form-control input", placeholder: "Contraseña", id: "login-password" %>
            </div>
          </div>          
          <div class="form-group">
            <div >
              <div class="checkbox login-remember">
                <label>
                  <% if devise_mapping.rememberable? -%>                  
                    <%= f.check_box :remember_me %> Recordarme                                   
                  <% end -%>
                </label> 
              </div>
            </div>
          </div>
          
          <div>
            <div>
              <%= f.submit "Iniciar Sesión", :class => 'btn btn-block btn-lg btn-primary' %>
            </div>
          </div>
          <!--userForm--> 
        <% end %>
      </div>
      <div class="modal-footer">
        <p class="text-center"> ¿Aún no tienes cuenta? <a data-toggle="modal"  data-dismiss="modal" href="#ModalSignup"> Registrate Aqui </a> <br>
          <%= link_to "¿Olvidaste tu contraseña?", new_user_password_path %></p>
      </div>
    </div>
    <!-- /.modal-content --> 
    
  </div>
  <!-- /.modal-dialog --> 
  
</div>
<!-- /.Modal Login --> 

app/views/pages/_sign_up_modal.html.erb
<!-- Modal Signup start -->
<div class="modal signUpContent fade" id="ModalSignup" tabindex="-1" role="dialog" >
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"> &times; </button>
        <h3 class="modal-title-site text-center" > REGISTRARSE </h3>
      </div>
      <div class="modal-body">
        <div class="control-group">
          <%= link_to "REGISTRATE CON FACEBOOK", user_omniauth_authorize_path(:facebook), class: "fb_button btn  btn-block btn-lg" %>
        </div>        
        <h5 style="padding:10px 0 10px 0;" class="text-center"> O COMPLETA TUS DATOS PERSONALES </h5>

        <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
          <%= devise_error_messages! %>

          <div class="form-group reg-email">
            <div>
              <%= f.email_field :email, :autofocus => true, class: "form-control input", placeholder: "Email", id: "login-user" %>
            </div>
          </div>

          <div class="form-group reg-password">
            <div>
              <%= f.password_field :password, class: "form-control input", placeholder: "Contraseña - Mínimo 8 caracteres" %>
            </div>
          </div> 

          <div class="form-group reg-password">
            <div>
              <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control input", placeholder: "Confirmar contraseña" %>
            </div>
          </div>

          <div >
            <div >
              <%= f.submit "Registrarse", :class => 'btn btn-block btn-lg btn-primary' %>
            </div>
          </div>
          <!--userForm--> 

        <% end %>
      </div>
      <div class="modal-footer">
        <p class="text-center"> ¿Ya estas registrado? <a data-toggle="modal"  data-dismiss="modal" href="#ModalLogin"> Entra Aqui </a> </p>
      </div>
    </div>
    <!-- /.modal-content --> 
    
  </div>
  <!-- /.modal-dialog --> 
  
</div>
<!-- /.ModalSignup End --> 

app/views/pages/about_us.html.erb
	
<div class="parallax-section parallax-fx parallax-image-aboutus parallaxOffset no-padding">
  <div class="w100 ">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <div class="parallax-content clearfix animated ">
            <h1 class="x2large">
              ABOUT TSHOP 
            </h1>
            <h5 class="parallaxSubtitle">
              Lorem ipsum dolor sit amet consectetuer 
            </h5>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /.parallax -->

<div class="container main-container ">
  
  <div class="row innerPage">
    <div class="col-lg-12 col-md-12 col-sm-12">
      <div class="row userInfo">
        <div class="col-xs-12 col-sm-12">
          <h1 class="title-big text-center section-title-style2">
            <span >
              About us
            </span>
          </h1>
          
          <p class="lead text-center">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac augue at erat hendrerit dictum. Praesent porta, purus eget sagittis imperdiet, nulla mi ullamcorper metus, id hendrerit metus diam vitae est. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. 
          </p>
          
          
          <hr class="hr hr30">
          <div class="row animated">
            <div class="col-lg-4 col-md-4 col-sm-6 col-sm-6">
              <img class="img-responsive" src="images/site/girl1.jpg" alt="img">
              <h3 class="block-title-3">
                Consectetur adipiscing  
              </h3>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac augue at erat hendrerit dictum. Praesent porta, purus eget sagittis imperdiet, nulla mi ullamcorper metus, id hendrerit metus diam vitae est. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.
              </p>
              
              
              
            </div>
            
            <div class="col-lg-4 col-md-4 col-sm-6 col-sm-6">
              <img class="img-responsive" src="images/site/girl2.jpg" alt="img">
              <h3 class="block-title-3">
                Lorem ipsum dolor  
              </h3>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac augue at erat hendrerit dictum. Praesent porta, purus eget sagittis imperdiet, nulla mi ullamcorper metus, id hendrerit metus diam vitae est. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.
              </p>
              
            </div>
            
            <div class="col-lg-4 col-md-4 col-sm-6 col-sm-6">
              <img class="img-responsive" src="images/site/girl3.jpg" alt="img">
              <h3 class="block-title-3">
                Consectetur adipiscing 
              </h3>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac augue at erat hendrerit dictum. Praesent porta, purus eget sagittis imperdiet, nulla mi ullamcorper metus, id hendrerit metus diam vitae est. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.
              </p>
              
            </div>
            
            
            
          </div><!--/.row-->
          
          <hr>
        </div>
      </div>  <!--/row end-->
    </div>
  </div> <!--/.innerPage-->
  <div style="clear:both">  </div>
</div><!-- /.main-container -->


<div class="gap"> </div>

app/views/pages/home.html.erb
<script>
    paceOptions = {
      elements: true
    };
</script>

<div class="banner">
  <div class="full-container">
    <div class="slider-content">
      <ul id="pager" class="container">
      </ul>
      <div class="slider slider-v2">
        <div class="slider-item slider-item-img1 " data-cycle-pager-template="<a href=#> LATEST COLLECTION </a>">
          <div class="sliderInfo">
            <div class="container">
              <div class="col-lg-5 col-md-5 col-sm-5 pull-right sliderText dark alpha80 hidden-xs">
                <div class="inner">
                  <h1>LATEST COLLECTION</h1>
                  <p class="hidden-xs"> Lorem ipsum dolor sit amet, consectetuer adipiscing elit,
                    sed diam nonummy nibh euismod tincidunt ut
                    laoreet dolore magna aliquam erat volutpa </p>
                  <a  href="category.html" class="slide-link">SHOP NOW <span class="arrowUnicode">►</span></a> </div>
              </div>
            </div>
          </div>
          <img  alt="img" src="<%= asset_path('slider/slider3.jpg') %>" class="img-responsive parallaximg sliderImg"> </div>
        <!--/.slider-item-->

        <div class="slider-item slider-item-img2  parallax" data-cycle-pager-template="<a href=#> WOMEN COLLECTION </a>">
          <div class="sliderInfo">
            <div class="container">
              <div class="col-lg-5 col-md-5 col-sm-5 pull-left sliderText dark alpha80 hidden-xs">
                <div class="inner">
                  <h1>WOMEN COLLECTION</h1>
                  <p class="hidden-xs"> Lorem ipsum dolor sit amet, consectetuer adipiscing elit,
                    sed diam nonummy nibh euismod tincidunt ut
                    laoreet dolore magna aliquam erat volutpa </p>
                  <a href="category.html"  class="slide-link">SHOP NOW <span class="arrowUnicode">►</span></a> </div>
              </div>
            </div>
          </div>
          <img alt="img" src="<%= asset_path('slider/slider4.jpg') %>" class="img-responsive parallaximg sliderImg"> </div>
        <!--/.slider-item-->

        <div class="slider-item slider-item-img3  parallax" data-cycle-pager-template="<a href=#> NEW COLLECTION </a>">
          <div class="sliderInfo">
            <div class="container">
              <div class="col-lg-4 col-md-4 col-sm-5 pull-right sliderText dark alpha80 transformRight hidden-xs">
                <div class="inner">
                  <h1>NEW COLLECTION</h1>
                  <p class="hidden-xs"> Lorem ipsum dolor sit amet, consectetuer adipiscing elit,
                    sed diam nonummy nibh euismod tincidunt ut
                    laoreet dolore magna aliquam erat volutpa </p>
                  <a href="category.html"  class="slide-link">SHOP NOW <span class="arrowUnicode">►</span></a> </div>
              </div>
            </div>
          </div>
          <img alt="img" src="<%= asset_path('slider/slider2.jpg') %>" class="img-responsive parallaximg sliderImg"> </div>
        <!--/.slider-item-->
      </div>
      <!--/.slider-v2-->
    </div>
    <!--/.slider-content-->
  </div>
  <!--/.full-container-->
</div>
<!--/.banner style2-->

<div class="container main-container">

  <!-- Main component call to action -->

  <div class="row featuredPostContainer globalPadding style2">
    <h3 class="section-title style2 text-center"><span>NUEVOS PRODUCTOS</span></h3>
    <div id="productslider" class="owl-carousel owl-theme">
      <% @last_articles.each do |article| %>
        <div class="item">
          <div class="product">
              <%= link_to "<i class='glyphicon glyphicon-heart'></i>".html_safe, whishlist_item_create_path(article), class: "add-fav" %>
            <div class="image">
              <div class="quickview">
                <a title="Quick View" class="btn btn-xs btn-quickview" modal-id="article-<%= article.id %>"> Vista Rápida </a>
              </div>
              <%= link_to "<img src='#{article.article_images.first.image.url(:medium)}' alt='img' class='img-responsive'>".html_safe, storehouses_article_path(article.id) %>
              <div class="promotion">
                <span class="new-product"> Nuevo</span>
                <!-- <span class="discount">15% OFF</span> -->
              </div>
            </div>
            <div class="description">
              <h4><%= link_to article.name, storehouses_article_path(article.id) %></h4>
              <p><%= article.details %> </p>
              <!-- <span class="size">XL / XXL / S </span> --> </div>
            <div class="price"> <span>$ <%= number_to_currency(article.price, unit: "", precision: 0) %></span> </div>
            <div class="action-control">
              <!-- <a class="btn btn-primary">
                <span class="add2cart">
                  <i class="glyphicon glyphicon-shopping-cart"> </i>
                  + Lista de deseos
                </span>
              </a> -->
              <%= link_to "<span class='add2cart'><i class='glyphicon glyphicon-shopping-cart'></i> Lista de deseos</span>".html_safe, whishlist_item_create_path(article), class: "btn btn-primary" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <!--/.productslider-->

  </div>
  <!--/.featuredPostContainer-->
</div>
<!-- /main container -->

<div class="parallax-section parallax-image-1">
  <div class="container">
    <div class="row ">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="parallax-content clearfix">
          <h1 class="parallaxPrce"> $200 </h1>
          <h2 class="uppercase">FREE INTERNATIONAL SHIPPING! Get Free Shipping Coupons</h2>
          <h3 > Energistically develop parallel mindshare rather than premier deliverables. </h3>
          <div style="clear:both"></div>
          <a class="btn btn-discover "> <i class="fa fa-shopping-cart"></i> SHOP NOW </a> </div>
      </div>
    </div>
    <!--/.row-->
  </div>
  <!--/.container-->
</div>
<!--/.parallax-image-1-->

<div class="container main-container">

  <!-- Main component call to action -->

  <h3 class="section-title style2 text-center"><span>TIENDAS REGISTRADAS</span></h3>
  <div class="width100 section-block">
    <h3 class="section-title"><span> BRAND</span> <a id="nextBrand" class="link pull-right carousel-nav"> <i class="fa fa-angle-right"></i></a> <a id="prevBrand" class="link pull-right carousel-nav"> <i class="fa fa-angle-left"></i> </a> </h3>
    <div class="row">
      <div class="col-lg-12">
        <ul class="no-margin brand-carousel owl-carousel owl-theme">

          <% @storehouses.each do |storehouse| %>
            <li><%= link_to "<img src='#{storehouse.avatar.url(:thumb)}' alt='img' >".html_safe, root_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
    <!--/.row-->
  </div>
  <!--/.section-block-->

  <hr class="no-margin-top">
  <div class="width100 section-block ">
    <div class="row featureImg">
      <div class="col-md-3 col-sm-3 col-xs-6"> <a href="category.html"><img src="<%= asset_path('site/new-collection-1.jpg') %>" class="img-responsive" alt="img" ></a> </div>
      <div class="col-md-3 col-sm-3 col-xs-6"> <a href="category.html"><img src="<%= asset_path('site/new-collection-2.jpg') %>" class="img-responsive" alt="img" ></a> </div>
      <div class="col-md-3 col-sm-3 col-xs-6"> <a href="category.html"><img src="<%= asset_path('site/new-collection-3.jpg') %>" class="img-responsive" alt="img" ></a> </div>
      <div class="col-md-3 col-sm-3 col-xs-6"> <a href="category.html"><img src="<%= asset_path('site/new-collection-4.jpg') %>" class="img-responsive" alt="img"></a> </div>
    </div>
    <!--/.row-->
  </div>
  <!--/.section-block-->

</div>
<!--main-container-->

<div class="parallax-section parallax-image-2">
  <div class="w100 parallax-section-overley">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <div class="parallax-content clearfix">
            <h1 class="xlarge"> Trusted Seller 500+ </h1>
            <h5 class="parallaxSubtitle"> Lorem ipsum dolor sit amet consectetuer </h5>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!--/.parallax-section-->

app/views/pages/stores.html.erb
<div class="container main-container headerOffset">

  <!-- Main component call to action -->

  <div class="row">
    <div class="breadcrumbDiv col-lg-12">
      <ul class="breadcrumb">
        <li> <a href="index.html">Home</a> </li>
        <li class="active">Tiendas </li>
      </ul>
    </div>
  </div>
  <!-- /.row  -->

  <div class="row">

    <!--left column-->

    <div class="col-lg-3 col-md-3 col-sm-12">
      <div class="panel-group" id="accordionNo">
        <!--Category-->
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title"> <a data-toggle="collapse"  href="#collapseCategory" class="collapseWill"> <span class="pull-left"> <i class="fa fa-caret-right"></i></span>Tiendas</a></h4>
          </div>
          <div id="collapseCategory" class="panel-collapse collapse in">
            <div class="panel-body">
              <ul class="nav nav-pills nav-stacked tree">
                <% @storehouses.each do |storehouse| %>
                  <% category_hash = storehouse_categories(storehouse) %>
                  <li class="active dropdown-tree" > <a  class="dropdown-tree-a" > <span class="badge pull-right"><%= category_hash.count %></span> <%= storehouse.name %> </a>
                    <ul class="category-level-2 dropdown-menu-tree">
                      <% category_hash.each do |category, subcategory| %>
                        <li class="dropdown-tree"> <a class="dropdown-tree-a"  href="#"> <%= category.name %></a>
                          <ul class="category-level-2 dropdown-menu-tree">
                            <% subcategory.each do |subcategory| %>
                              <li> <%= link_to subcategory.name.capitalize, storehouse_path(storehouse.id, :subcategory_id => subcategory.id) %></li>
                            <% end %>
                          </ul>
                        </li>
                      <% end %>
                    </ul>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
        <!--/Category menu end-->
      </div>
    </div>

    <!--right column-->
    <div class="col-lg-9 col-md-9 col-sm-12">
      <div class="w100 clearfix category-top">
        <h2> TIENDAS </h2>
        <div class="categoryImage"> <img src="<%= asset_path('site/category.jpg') %>" class="img-responsive" alt="img"> </div>
      </div>
      <!--/.category-top-->

      <div class="row subCategoryList clearfix">
        <% @storehouses.each do |storehouse| %>
          <div class="col-lg-2 col-md-2 col-sm-3 col-xs-4  text-center ">
            <div class="thumbnail equalheight"> 
              <%= link_to "<img src='#{storehouse.avatar.url}' class='img-rounded' alt='img'>".html_safe, storehouse_path(storehouse.id), class: "subCategoryThumb" %>
              <%= link_to "<span>#{storehouse.name}</span>".html_safe, storehouse_path(storehouse.id) %>
            </div>
          </div>
        <% end %>
      </div>
      <!--/.subCategoryList-->