config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'pages#home'
  get 'about_us' => 'pages#about_us'
  get 'stores' => 'pages#stores'
  get '/storehouses/articles/list_subcategories'
  get 'subcategory_products' => 'admin/subcategories#show_products'
  get 'favoritos', to: 'whishlist_items#index'
  get "/storehouses/favorite_articles"
  get "/storehouses/favorite_clients"

  resources :whishlist_items do
    get 'create', to: 'whishlist_items#create'
  end


  # devise_scope :user do
  #   get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end

  namespace :admin do
    resources :storehouses
    resources :categories
    resources :subcategories
    resources :user, :controller => "user"
    get 'user_list' => 'user#user_index'
    get 'article_list' => 'user#article_index'
    get 'edit_user' => 'user#edit_user'
    patch 'update_user' => 'user#update_user'
  end

   namespace :storehouses do
    resources :articles do
      get "bindstore", to: "articles#bindstore",  as: "bindstore"
    end
  end

  resources :storehouses do
    get 'subcategories_list', on: :member
  end
end

# http://localhost:3000/storehouses/json/1.json
# http://localhost:3000/storehouses/article/json/1.json

app/views/layouts/_contact_storehouse_modal.html.erb
<div id="article-storebind-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="col-md-6 col-md-offset-3 m-top-1">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h3 class="text-center m-top-1">Información de tienda:</h3>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-md-6">
            <img src="" class="img-responsive store-largeimg" alt="img">
          </div>
          <div class="col-md-6">
          <div style="padding:2em;">
              <h1 class="store-title"></h1>
              <h3 class="store-telephone"><i class='fa fa-phone'></i><i class="small"> telefono</i><br><span></span></h3>
              <h3 class="store-whatsapp"><i class='fa fa-whatsapp'></i><i class="small"> whatsapp</i><br><span></span></h3>
              <h3 class="store-email"><i class='fa fa-envelope'></i><i class="small"> email</i><br><span></span></h3>
              <h3 class="store-adress"><i class='fa fa-map-marker'></i><i class="small"> dirección:</i><br><span></span></h3>
              <div class="store-description">
                <p></p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button class="btn btn-default" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>
<script>
  $( "body" ).on( "click", ".btn-article-storebind", function() {
    articleId = $(this).attr('modal-id').split('article-')[1]
    $.getJSON( "/storehouses/articles/"+ articleId +"/bindstore.json" ).done(function( json ) {
      console.log(json);
      $('#article-storebind-modal .store-largeimg').attr('src', json.image )
      $('#article-storebind-modal .store-title').text(json.name)
      $('#article-storebind-modal .store-telephone span').text(" "+ json.awesome_telephone)
      $('#article-storebind-modal .store-whatsapp span').text(" "+ json.awesome_whatsapp)
      $('#article-storebind-modal .store-email span').text(" "+ json.email)
      $('#article-storebind-modal .store-adress span').text(" "+ json.address)
      $('#article-storebind-modal .store-description p').text(" "+ json.description)
      $('#article-storebind-modal').modal('show')
    }).fail(function( jqxhr, textStatus, error ) {
      var err = textStatus + ", " + error;
      console.log( "Request Failed: " + err );
    });
  });
</script>

app/views/layouts/_favoritelist.html.erb
<!-- this part is duplicate from cartMenu  keep it for mobile -->
<div class="navbar-cart collapse">
  <div class="cartMenu  col-lg-4 col-xs-12 col-md-4 ">
   <%= render 'layouts/favoritelist_items' %>
   <!--/.miniCartTable-->
   <div class="miniCartFooter  miniCartFooterInMobile text-right">
    <h3 class="text-right subtotal"> Subtotal: $<%= favorite_total_price if user_signed_in? %> </h3>
    <%= link_to "<i class='glyphicon glyphicon-heart'> </i> VER FAVORITOS".html_safe, favoritos_path, class: "btn btn-sm btn-primary" %>
  </div>
  <!--/.miniCartFooter-->
</div>
<!--/.cartMenu-->
</div>
<!--/.navbar-cart-->

app/views/layouts/_favoritelist_items.html.erb
<% if user_signed_in?  %>
  <div class="w100 miniCartTable scroll-pane favorite-list-items">
    <table>
      <tbody>
        <% favorite_list if user_signed_in? %>
        <% if favorite_counter > 0 %>
          <% @favitems.each do |item| %>
          <tr class="miniCartProduct">
            <td style="width:20%" class="miniCartProductThumb"><div><%= link_to "<img src=' #{item.article.article_images.first.image.url}' alt='img'>".html_safe , storehouses_article_path( item.article) %></div></td>
            <td style="width:40%"><div class="miniCartDescription">
              <h4> <%= link_to item.article.name , storehouses_article_path( item.article)  %></h4>
              <span class="size"> <%= item.article.code %> </span>
              <div class="price"> <span> $ <%= number_with_delimiter(item.article.price, :delimiter => ',') %> </span> </div>
            </div></td>
            <td  style="width:10%" class="miniCartQuantity"><a > X 1 </a></td>
            <td  style="width:15%" class="miniCartSubtotal"><span>  $ <%= number_with_delimiter(item.article.price, :delimiter => ',')  %> </span></td>
            <td  style="width:5%" class="delete"><a > x </a></td>
          </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="footer">
    <div class="container">
      <div class="row">
        <div class="col-lg-3  col-md-3 col-sm-4 col-xs-6">
          <h3> Servicio al cliente </h3>
          <ul>
            <li class="supportLi">
              <p> Puedes contactar el equipo de Ventas El Hueco en el siguiente número telefónico: </p>
              <h4> <a class="inline" href="callto:+8801680531352"> <strong> <i class="fa fa-phone"> </i> 88 01680 531352 </strong> </a> </h4>
              <h4> <a class="inline" href="mailto:help@tshopweb.com"> <i class="fa fa-envelope-o"> </i> help@tshopweb.com </a> </h4>
            </li>
          </ul>
        </div>
        <div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
          <h3> Ir a </h3>
          <ul>
            <li><%= link_to 'Ver Tiendas', stores_path %></li>
            <% Category.order("RANDOM()").limit(5).each do |category| %>
              <li><%= link_to category.name.capitalize, stores_path %></li>
            <% end %>

          </ul>
        </div>
        <div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
          <h3> Información </h3>
          <ul>          
            <li><%= link_to 'Sobre Nosotros', about_us_path %></li>
          </ul>
        </div>
        <% if user_signed_in? %>
          <div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
            <h3> Mi cuenta</h3>
            <ul>              
              <li><%= link_to "Mi Cuenta", admin_edit_user_path(:id => current_user.id) %></li>
              <li><%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete %></li>
            </ul>
          </div>
        <% else %>
          <div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
            <h3> Mi cuenta</h3>
            <ul>
              <li> <%= link_to "Iniciar Sesión", new_user_session_path %> </li>
              <li> <%= link_to "Registrarse", new_user_registration_path %> </li>
            </ul>
          </div>
        <% end %>
        <div class="col-lg-3  col-md-3 col-sm-6 col-xs-12 ">
          <h3> Contactanos </h3>
          <ul>
            <li>
              <div class="input-append newsLatterBox text-center">
                <input type="text" class="full text-center"  placeholder="Escribe tu correo electrónico">
                <input type="text" class="full text-center"  placeholder="Escribe tu mensaje">
                <button class="btn  bg-gray" type="button"> Enviar <i class="fa fa-long-arrow-right"> </i> </button>
              </div>
            </li>
          </ul>
          <ul class="social">
            <li> <a href="http://facebook.com"> <i class=" fa fa-facebook"> &nbsp; </i> </a> </li>
            <li> <a href="http://twitter.com"> <i class="fa fa-twitter"> &nbsp; </i> </a> </li>
            <li> <a href="https://plus.google.com"> <i class="fa fa-google-plus"> &nbsp; </i> </a> </li>
            <li> <a href="http://youtube.com"> <i class="fa fa-pinterest"> &nbsp; </i> </a> </li>
            <li> <a href="http://youtube.com"> <i class="fa fa-youtube"> &nbsp; </i> </a> </li>
          </ul>
        </div>
      </div>
      <!--/.row-->
    </div>
    <!--/.container-->
  </div>
  <!--/.footer-->

  <div class="footer-bottom">
    <div class="container text-center">
      <p class="pull-left"> Developed By: <strong><a class="kaizen" href="http://kaizendevs.co" target="_blank">Kaizen Devs</a></strong> </p>
      <!-- <div class="pull-right paymentMethodImg"> <img height="30" class="pull-right" src="<%= asset_path('site/payment/master_card.png') %>" alt="img" > <img height="30" class="pull-right" src="<%= asset_path('site/payment/paypal.png') %>" alt="img" > <img height="30" class="pull-right" src="<%= asset_path('site/payment/american_express_card.png') %>" alt="img" > <img  height="30" class="pull-right" src="<%= asset_path('site/payment/discover_network_card.png') %>" alt="img" > <img  height="30" class="pull-right" src="<%= asset_path('site/payment/google_wallet.png') %>" alt="img" > </div> -->
    </div>
  </div>
  <!--/.footer-bottom-->
</footer>

app/views/layouts/_item_modal.html.erb
<div class="modal fade" id="product-details-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <button aria-hidden="true" data-dismiss="modal" class="close" type="button"> × </button>
            <div class="col-lg-5 col-md-5 col-sm-5  col-xs-12">
                <div class="main-image  col-lg-12 no-padding style3">
                    <a class="product-largeimg-link" href="">
                    <img src="" class="img-responsive product-largeimg" alt="img">
                    </a>
                </div>
            </div>
            <div class="col-lg-7 col-md-7 col-sm-7 col-xs-12 modal-details no-padding">
                <div class="modal-details-inner">
                    <h1 class="product-title"></h1>
                    <h3 class="product-code"></h3>
                    <div class="product-price"> <span class="price-sales"> $70</span></div>
                    <div class="details-description">
                        <p></p>
                    </div>
                    <div class="cart-actions">
                        <div class="addto">
                            <a class="link-wishlist wishlist add-to-wishlist">
                                <i class="glyphicon glyphicon-shopping-cart"> </i> Lista de deseos
                            </a>
                        </div>
                    </div>
                    <div class="product-share clearfix">
                        <p> SHARE </p>
                        <div class="socialIcon">
                            <a href="#"> <i class="fa fa-facebook"></i>
                            </a>
                            <a href="#"> <i class="fa fa-twitter"></i>
                            </a>
                            <a href="#"> <i class="fa fa-google-plus"></i>
                            </a>
                            <a href="#"> <i class="fa fa-pinterest"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="clear"></div>
        </div>
    </div>
</div>
<script>

    $( "body" ).on( "click", ".btn-quickview", function() {
        articleId = $(this).attr('modal-id').split('article-')[1]
        $.getJSON( "/storehouses/articles/" + articleId + ".json" ).done(function( json ) {
            $('#product-details-modal .product-largeimg-link').attr('href', "/storehouses/articles/" + json.id )
            $('#product-details-modal .product-largeimg-link img').attr('src', json.image )
            $('#product-details-modal .add-to-wishlist').attr('href', "/whishlist_items/" + json.id + "/create" )

            $('#product-details-modal .product-title').text(json.name)
            $('#product-details-modal .product-code').text('Código de producto: '+ json.code)
            $('#product-details-modal .price-sales').text('$'+ json.price_with_coma)
            $('#product-details-modal .details-description p').text(json.details)

            $('#product-details-modal').modal('show')
        }).fail(function( jqxhr, textStatus, error ) {
            var err = textStatus + ", " + error;
            console.log( "Request Failed: " + err );
        });
  });
</script>

app/views/layouts/_nav.html.erb
<!-- Fixed navbar start -->
<div class="navbar navbar-tshop navbar-fixed-top megamenu" role="navigation">
  <div class="navbar-top">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 col-sm-6 col-xs-6 col-md-6">
        <% if user_signed_in? %>
          <div class="pull-left ">
              <ul class="userMenu ">
                <li> <a href="#"> <span class="hidden-xs">HOLA</span><i class="glyphicon glyphicon-info-sign hide visible-xs "></i> </a> </li>
                <li class="phone-number">
                <a  href="callto:+8801680531352">
                <span> <i class="glyphicon glyphicon-user"></i></span>
                <span class="hidden-xs" style="margin-left:5px"> <%= current_user.email %> </span> </a> </li>
              </ul>
            </div>
          </div>
        <% else %>
          <div class="pull-left ">
              <ul class="userMenu ">
                <li> <a href="#"> <span class="hidden-xs">Contactanos en:</span><i class="glyphicon glyphicon-info-sign hide visible-xs "></i> </a> </li>
                <li class="phone-number">
                <a  href="callto:+8801680531352">
                <span> <i class="glyphicon glyphicon-user"></i></span>
                <span class="hidden-xs" style="margin-left:5px"> info@ventaselhueco.co </span> </a> </li>
              </ul>
            </div>
          </div>
        <% end %>
        <div class="col-lg-6 col-sm-6 col-xs-6 col-md-6 no-margin no-padding">
          <div class="pull-right">
            <ul class="userMenu">
              <% if user_signed_in? %>
                <li><%= link_to "<span class='hidden-xs'> Mi Cuenta</span> <i class='glyphicon glyphicon-user hide visible-xs'></i>".html_safe, admin_edit_user_path(:id => current_user.id) %></li>
                <li><%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to "Entrar", "#ModalLogin", "data-toggle" => "modal" %></li>
                <li class="hidden-xs"><%= link_to "Registrarse", "#ModalSignup", "data-toggle" => "modal" %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!--/.navbar-top-->

  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"> <span class="sr-only"> Toggle navigation </span> <span class="icon-bar"> </span> <span class="icon-bar"> </span> <span class="icon-bar"> </span> </button>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-cart"> <i class="fa fa-shopping-cart colorWhite"> </i> <span class="cartRespons colorWhite"> FAVORITOS($<%= favorite_total_price %>) </span> </button>
      <%= link_to root_path do %>
         <%= image_tag "http://i592.photobucket.com/albums/tt5/Mardini03/freeformatter.png", class: "navbar-brand" %>
      <% end %>


      <!-- this part for mobile -->
      <div class="search-box pull-right hidden-lg hidden-md hidden-sm">
        <div class="input-group">
          <button class="btn btn-nobg getFullSearch" type="button"> <i class="fa fa-search"> </i> </button>
        </div>
        <!-- /input-group -->
      </div>
    </div>

    <!-- AQUI IBA EL COLAPSE DEL CARRITO -->
    <!-- AQUI IBA EL COLAPSE DEL CARRITO -->
    <!-- AQUI IBA EL COLAPSE DEL CARRITO -->
    <!-- this part is duplicate from cartMenu  keep it for mobile -->
    <div class="navbar-cart  collapse">
      <div class="cartMenu  col-lg-4 col-xs-12 col-md-4 ">
        <div class="w100 miniCartTable scroll-pane">
          <%= render 'layouts/favoritelist_items' %>          
        </div>
        <!--/.miniCartTable-->
        
        <div class="miniCartFooter text-right">
          <h3 class="text-right subtotal"> Subtotal: $<%= favorite_total_price %> </h3>
          <%= link_to "<i class='glyphicon glyphicon-heart'> </i> VER FAVORITOS".html_safe, favoritos_path, class: "btn btn-sm btn-primary" %>
        </div>
        <!--/.miniCartFooter--> 
        
      </div>
      <!--/.cartMenu--> 
    </div>
    <!--/.navbar-cart-->


    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">

        <% if user_signed_in? && current_user.admin? %>
          <li class="dropdown "> <a href="#" class="dropdown-toggle" data-toggle="dropdown">ADMIN<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li class="dropdown-header">Agregar o Listar Tiendas</li>
              <li> <%= link_to "Nueva Tienda", new_admin_user_path  %></li>
              <li> <%= link_to "Tiendas Registradas", admin_user_index_path %></li>
              <li class="dropdown-header">Listar Artículos</li>
              <li> <%= link_to "Artículos Registrados", admin_article_list_path %></li>
              <li class="dropdown-header">Listar Usuarios</li>
              <li> <%= link_to "Usuarios Registrados", admin_user_list_path %></li>
            </ul>
          </li>
          <li class="dropdown "> <a href="#" class="dropdown-toggle" data-toggle="dropdown"> CATEGORIAS <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li class="dropdown-header">Agregar o Listar Categorías</li>
              <li> <%= link_to "Nueva Categoría", new_admin_category_path  %> </li>
              <li> <%= link_to "Categorías Registradas", admin_categories_path  %> </li>
              <li> <%= link_to "Nueva Subcategoría", new_admin_subcategory_path %> </li>
              <li> <%= link_to "Subcategorías Registradas", admin_subcategories_path %> </li>
            </ul>
          </li>
        <% end %>

        <% if (user_signed_in? && current_user.tent?) %>          
          <li class="dropdown "> <a href="#" class="dropdown-toggle" data-toggle="dropdown"> MI TIENDA <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li class="dropdown-header">Ver o Editar Mi Tienda</li>
              <li> <%= link_to "Ver Tienda", admin_user_path(current_user.id)  %> </li>
              <li> <%= link_to "Editar Tienda", edit_admin_user_path(current_user.id)  %> </li>
              <li class="dropdown-header">Agregar o Listar Mis Artículos</li>
              <li> <%= link_to "Nuevo Artículo", new_storehouses_article_path  %> </li>
              <li> <%= link_to "Artículos Publicados", storehouses_articles_path  %> </li>
              <li class="dropdown-header">Favoritos de Mi tienda</li>
              <li><%= link_to "Favoritos", storehouses_favorite_articles_path %></li>
            </ul>
          </li>
          
        <% end %>

        <!-- change width of megamenu = use class > megamenu-fullwidth, megamenu-60width, megamenu-40width -->
        <li class="dropdown megamenu-80width "> <a data-toggle="dropdown" class="dropdown-toggle" href="#"> ARTICULOS <b class="caret"> </b> </a>
          <ul class="dropdown-menu">
            <li class="megamenu-content">

              <!-- megamenu-content -->
              <% categories = Category.all.limit(6) %>
              <% categories.each do |category| %>
                <ul class="col-lg-2  col-sm-2 col-md-2  unstyled noMarginLeft">
                  <li>
                    <p> <strong> <%= category.name %> </strong> </p>
                  </li>
                  <% category.subcategories.sort_by(&:name).each do |subcategory| %>
                    <li> <%= link_to subcategory.name, subcategory_products_path(:subcategory_id => subcategory.id) %></li>
                  <% end %>
                </ul>
              <% end %>
            </li>
          </ul>
        </li>
        <li class="dropdown megamenu-fullwidth"><%= link_to 'Ver Tiendas', stores_path %></li>
        <li class="dropdown megamenu-fullwidth"><%= link_to 'Sobre Nosotros', about_us_path %></li>
      </ul>

        <!--- this part will be hidden for mobile version -->
        <div class="nav navbar-nav navbar-right hidden-xs">
          <% if user_signed_in? %>
          <div class="dropdown cartMenu"> <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <i class="glyphicon glyphicon-heart"> </i> <span class="cartRespons"> Favoritos ($<%= favorite_total_price %> ) </span> <b class="caret"> </b> </a>
            <div class="dropdown-menu col-lg-4 col-xs-12 col-md-4 ">
              <%= render 'layouts/favoritelist_items' %>
              <div class="miniCartFooter text-right">
                <h3 class="text-right subtotal"> Subtotal: $<%= favorite_total_price %> </h3>
                <%= link_to "<i class='glyphicon glyphicon-heart'> </i> VER FAVORITOS".html_safe, favoritos_path, class: "btn btn-sm btn-primary" %>
              </div>
            </div>
          </div>
          <% end %>
          <div class="search-box">
            <div class="input-group">
              <button class="btn btn-nobg getFullSearch" type="button"> <i class="fa fa-search"> </i> </button>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!--/.container -->
    <div class="search-full text-right"> <a class="pull-right search-close"> <i class=" fa fa-times-circle"> </i> </a>
      <div class="searchInputBox pull-right">
        <input type="search"  data-searchurl="search?=" name="q" placeholder="start typing and hit enter to search" class="search-input">
        <button class="btn-nobg search-btn" type="submit"> <i class="fa fa-search"> </i> </button>
      </div>
    </div>
    <!--/.search-full-->
  </div>
<!-- /.Fixed navbar  -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- Fav and touch icons -->
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="<%= asset_path('ico/apple-touch-icon-144-precomposed.png') %>">
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="<%= asset_path('ico/apple-touch-icon-144-precomposed.png') %>">
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="<%= asset_path('ico/apple-touch-icon-72-precomposed.png') %>">
  <link rel="apple-touch-icon-precomposed" href="<%= asset_path('ico/apple-touch-icon-57-precomposed.png') %>">
  <link rel="shortcut icon" href="<%= asset_path('ico/favicon.png') %>">
  <title>Ventas El Hueco</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="pace-done">
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '1617157328519545',
      xfbml      : true,
      version    : 'v2.3'
    });
  };
  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>

<%= render "pages/login_modal" %>

<%= render "pages/sign_up_modal" %>

<%= render "layouts/nav" %>


<% if flash[:alert] %>
  <div class="alertOffset">
      <div class="alert alert-danger text-center" role="alert">
        <%=flash[:alert]%>
        <span class="right-text text-right">X</span>
    </div>
  </div>
<%end%>

<% if flash[:notice] %>
  <div class="alertOffset">
      <div class="alert alert-success text-center" role="alert">
        <%=flash[:notice]%>
        <span class="text-right">X</span>
      </div>
  </div>
<%end%>

<%= yield %>

<%= render 'layouts/footer' %>

<%= render "layouts/item_modal" %>

<%= render "layouts/contact_storehouse_modal" %>

</body>
</html>